function daysAgo(n) {
  return new Date(Date.now() - n * 86400000).toISOString();
}

export const NOTIFICATIONS_SEED = [
  {
    id: "N001",
    type: "approved",
    title: "Registration Approved",
    body: "Your registration for Spring Classic (Thunder Bolt) has been approved.",
    time: daysAgo(0),
    read: false,
    forRoles: ["jockey"],
    forUserId: null,
  },
  {
    id: "N002",
    type: "pending",
    title: "Pending Review",
    body: "Registration for Derby Cup (Iron Fist) is awaiting admin approval.",
    time: daysAgo(1),
    read: false,
    forRoles: ["jockey"],
    forUserId: "U004",
  },
  {
    id: "N003",
    type: "race_reminder",
    title: "Race Reminder",
    body: "Spring Classic starts in 3 days at Churchill Downs. Please confirm your attendance.",
    time: daysAgo(2),
    read: false,
    forRoles: ["jockey"],
    forUserId: null,
  },
  {
    id: "N004",
    type: "info",
    title: "Tournament Update",
    body: "The Grand Prix Championship Series 2025 registration deadline has been extended to April 15.",
    time: daysAgo(3),
    read: true,
    forRoles: ["jockey", "owner"],
    forUserId: null,
  },
  {
    id: "N005",
    type: "approved",
    title: "Horse Approved",
    body: "Thunder Bolt (Miguel Torres) has been approved to compete in Spring Classic.",
    time: daysAgo(0),
    read: false,
    forRoles: ["owner"],
    forUserId: "U006",
  },
  {
    id: "N006",
    type: "pending",
    title: "Pending: Silver Arrow",
    body: "Registration for Silver Arrow (Carlos Ruiz) in Spring Classic is awaiting approval.",
    time: daysAgo(1),
    read: false,
    forRoles: ["owner"],
    forUserId: "U007",
  },
  {
    id: "N007",
    type: "rejected",
    title: "Registration Rejected",
    body: "Desert Storm (James O'Brien) for Derby Cup was rejected. Reason: incomplete documentation.",
    time: daysAgo(2),
    read: true,
    forRoles: ["owner"],
    forUserId: "U006",
  },
  {
    id: "N008",
    type: "race_reminder",
    title: "Upcoming Race Notice",
    body: "Golden Handicap at Santa Anita is scheduled in 14 days. Ensure your horse is race-ready.",
    time: daysAgo(4),
    read: true,
    forRoles: ["owner"],
    forUserId: null,
  },
];
