import { uid } from "./constants";

export const RACES_SEED = [
  {
    id: "RACE01",
    name: "Spring Classic",
    venue: "Churchill Downs",
    date: "2025-04-15",
    time: "14:00",
    distance: 1600,
    grade: "G1",
    prizePool: 500000,
    condition: "Firm",
    status: "Upcoming",
    refereeId: null,
    registrations: [
      {
        id: 1,
        submittedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
        ownerName: "Sunrise Stables",
        horseName: "Thunder Bolt",
        horseAge: 4,
        horseColor: "Bay",
        jockeyName: "Miguel Torres",
        licenseNo: "JLN-4821",
        trainerName: "Williams",
        raceName: "Spring Classic",
        grade: "G1",
        status: "Approved",
        note: "",
      },
      {
        id: 2,
        submittedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
        ownerName: "Blue River Farm",
        horseName: "Silver Arrow",
        horseAge: 5,
        horseColor: "Grey",
        jockeyName: "Carlos Ruiz",
        licenseNo: "JLN-7156",
        trainerName: "García",
        raceName: "Spring Classic",
        grade: "G1",
        status: "Approved",
        note: "",
      },
      {
        id: 3,
        submittedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
        ownerName: "Nightfall Racing",
        horseName: "Dark Knight",
        horseAge: 3,
        horseColor: "Black",
        jockeyName: "Emma Sinclair",
        licenseNo: "JLN-3390",
        trainerName: "Brown",
        raceName: "Spring Classic",
        grade: "G1",
        status: "Pending",
        note: "",
      },
      {
        id: 4,
        submittedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
        ownerName: "Desert Run LLC",
        horseName: "Desert Storm",
        horseAge: 4,
        horseColor: "Chestnut",
        jockeyName: "James O'Brien",
        licenseNo: "JLN-2047",
        trainerName: "Davis",
        raceName: "Spring Classic",
        grade: "G1",
        status: "Rejected",
        note: "Incomplete documentation",
      },
      {
        id: 9,
        submittedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
        ownerName: "Thunder Ranch",
        horseName: "Storm Rider",
        horseAge: 4,
        horseColor: "Black",
        jockeyName: "Liam Foster",
        licenseNo: "JLN-2048",
        trainerName: "Martinez",
        raceName: "Spring Classic",
        grade: "G1",
        status: "Pending",
        note: "",
      },
    ],
  },
  {
    id: "RACE02",
    name: "Derby Cup",
    venue: "Royal Ascot",
    date: "2025-05-20",
    time: "15:30",
    distance: 2000,
    grade: "G1",
    prizePool: 750000,
    condition: "Good",
    status: "Upcoming",
    refereeId: "R01",
    registrations: [
      {
        id: 10,
        submittedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
        ownerName: "Golden Gate Stables",
        horseName: "Golden Flash",
        horseAge: 4,
        horseColor: "Chestnut",
        jockeyName: "Yuki Tanaka",
        licenseNo: "JLN-3891",
        trainerName: "Smith",
        raceName: "Derby Cup",
        grade: "G1",
        status: "Approved",
        note: "",
      },
      {
        id: 11,
        submittedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
        ownerName: "Iron Forge Racing",
        horseName: "Iron Fist",
        horseAge: 5,
        horseColor: "Bay",
        jockeyName: "Lucas Martini",
        licenseNo: "JLN-5512",
        trainerName: "Williams",
        raceName: "Derby Cup",
        grade: "G1",
        status: "Pending",
        note: "",
      },
      {
        id: 14,
        submittedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
        ownerName: "Silver Moon Stables",
        horseName: "Midnight Thunder",
        horseAge: 5,
        horseColor: "Grey",
        jockeyName: "Nina Rodriguez",
        licenseNo: "JLN-3512",
        trainerName: "Williams",
        raceName: "Derby Cup",
        grade: "G1",
        status: "Approved",
        note: "",
      },
      {
        id: 15,
        submittedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
        ownerName: "Coastal Breeze Farm",
        horseName: "Coastal Wind",
        horseAge: 3,
        horseColor: "Chestnut",
        jockeyName: "Oliver James",
        licenseNo: "JLN-4829",
        trainerName: "García",
        raceName: "Derby Cup",
        grade: "G1",
        status: "Pending",
        note: "",
      },
    ],
  },
  {
    id: "RACE03",
    name: "Mid-Season Stakes",
    venue: "Flemington",
    date: "2025-06-10",
    time: "13:00",
    distance: 1400,
    grade: "G2",
    prizePool: 250000,
    condition: "Soft",
    status: "Upcoming",
    refereeId: "R02",
    registrations: [
      {
        id: 16,
        submittedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
        ownerName: "Phantom LLC",
        horseName: "Phantom Rider",
        horseAge: 4,
        horseColor: "Black",
        jockeyName: "Sofia Costa",
        licenseNo: "JLN-6134",
        trainerName: "Davis",
        raceName: "Mid-Season Stakes",
        grade: "G2",
        status: "Approved",
        note: "",
      },
      {
        id: 17,
        submittedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
        ownerName: "Azure Farms",
        horseName: "Blue Horizon",
        horseAge: 3,
        horseColor: "Grey",
        jockeyName: "Andre Blanc",
        licenseNo: "JLN-7123",
        trainerName: "Brown",
        raceName: "Mid-Season Stakes",
        grade: "G2",
        status: "Approved",
        note: "",
      },
      {
        id: 18,
        submittedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
        ownerName: "Red Rock Stables",
        horseName: "Red Wind",
        horseAge: 4,
        horseColor: "Chestnut",
        jockeyName: "Priya Patel",
        licenseNo: "JLN-8234",
        trainerName: "García",
        raceName: "Mid-Season Stakes",
        grade: "G2",
        status: "Pending",
        note: "",
      },
      {
        id: 19,
        submittedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
        ownerName: "Summit Ridge Ranch",
        horseName: "Summit Star",
        horseAge: 4,
        horseColor: "Bay",
        jockeyName: "Hannah Blake",
        licenseNo: "JLN-6134",
        trainerName: "Davis",
        raceName: "Mid-Season Stakes",
        grade: "G2",
        status: "Approved",
        note: "",
      },
    ],
  },
  {
    id: "RACE04",
    name: "Golden Handicap",
    venue: "Santa Anita",
    date: "2025-07-05",
    time: "16:00",
    distance: 1800,
    grade: "G3",
    prizePool: 150000,
    condition: "Fast",
    status: "Upcoming",
    refereeId: null,
    registrations: [],
  },
];
