export const USERS = [
  {
    id: "U001",
    role: "admin",
    name: "Alex Morgan",
    email: "admin@grandprix2025.com",
    phone: "+1 555 0100",
    org: "International Racing Federation",
    bio: "Tournament administrator overseeing all races and registrations.",
  },
  {
    id: "U002",
    role: "host",
    name: "Sarah Whitfield",
    email: "host@churchilldowns.com",
    phone: "+1 555 0200",
    org: "Churchill Downs",
    venue: "Churchill Downs",
    bio: "Venue host coordinating on-site race operations.",
  },
  {
    id: "U003",
    role: "jockey",
    name: "Miguel Torres",
    email: "miguel.torres@racing.com",
    phone: "+1 555 0301",
    licenseNo: "JLN-4821",
    bio: "Professional jockey — 8 years experience.",
  },
  {
    id: "U004",
    role: "jockey",
    name: "Carlos Ruiz",
    email: "carlos.ruiz@racing.com",
    phone: "+1 555 0302",
    licenseNo: "JLN-7156",
    bio: "G1 specialist with multiple championship wins.",
  },
  {
    id: "U005",
    role: "jockey",
    name: "Emma Sinclair",
    email: "emma.sinclair@racing.com",
    phone: "+1 555 0303",
    licenseNo: "JLN-3390",
    bio: "Rising star in international flat racing.",
  },
  {
    id: "U006",
    role: "owner",
    name: "Robert Blackwell",
    email: "robert@sunrisestables.com",
    phone: "+1 555 0401",
    org: "Sunrise Stables",
    bio: "Owner of Sunrise Stables, competing in the Grand Prix Championship.",
  },
  {
    id: "U007",
    role: "owner",
    name: "Diana Chen",
    email: "diana@blueriverfarm.com",
    phone: "+1 555 0402",
    org: "Blue River Farm",
    bio: "Proud owner of Blue River Farm racing team.",
  },
  {
    id: "U008",
    role: "referee",
    name: "James O'Brien",
    email: "james.ref@racing.com",
    phone: "+1 555 0501",
    bio: "Certified referee with 12 years of experience in international flat racing.",
  },
  {
    id: "U009",
    role: "spectator",
    name: "Lisa Spectator",
    email: "lisa.spectator@heritageracing.com",
    phone: "+1 555 0601",
    bio: "Racing enthusiast and regular spectator at Grand Prix events.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    joinDate: "2024-01-15",
    totalBets: 24,
    activeBets: 4,
    lifetimePayouts: 12400,
    totalStaked: 1450,
    winRate: 75,
  },
  {
    id: "U010",
    role: "spectator",
    name: "John Smith",
    email: "john.smith@test.com",
    phone: "+1 555 0602",
    bio: "Horse racing fan from New York.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    joinDate: "2024-03-22",
    totalBets: 12,
    activeBets: 2,
    lifetimePayouts: 5200,
    totalStaked: 680,
    winRate: 66,
  },
];

export const ROLE_LABELS = {
  admin:     "Administrator",
  host:      "Venue Host",
  jockey:    "Jockey",
  owner:     "Horse Owner",
  referee:   "Referee",
  spectator:  "Spectator",
};

export const ROLE_HOME = {
  admin:     "Admin Panel",
  host:      "Host Dashboard",
  jockey:    "My Races",
  owner:     "My Stables",
  referee:   "Referee Dashboard",
  spectator:  "Spectator Dashboard",
};
