spring:
  application:
    name: horse-racing
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=horse_racing_db;encrypt=false;trustServerCertificate=true
    username: sa
    password: 
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

jwt:
  secret: yourSecretKeyMustBeVeryLongAndSecureAtLeast256BitsForHS256AlgorithmYourSecretKeyMustBeVeryLongAndSecure
  expiration: 86400000

server:
  port: 8080
